apiVersion: v1
kind: Service
metadata:
  name: client-node-port
spec:
# NodePort is for dev purposes only, with some exceptions.
# NodePort ranges between 30000 and 32767
  type: NodePort
  ports:
    - port: 3050
      targetPort: 3000
      nodePort: 31515
  selector:
    component: web